#ddev-generated
services:
  mcp-inspector:
    container_name: ddev-${DDEV_SITENAME}-mcp-inspector
    image: node:22-alpine
    restart: "no"
    user: "${DDEV_UID}:${DDEV_GID}"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: ${DDEV_PROJECT_TYPE}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      - CLIENT_PORT=6274
      - SERVER_PORT=6277
      - DANGEROUSLY_OMIT_AUTH=true
      - HOST=0.0.0.0
      - MCP_SERVER_REQUEST_TIMEOUT=10000
      - MCP_REQUEST_TIMEOUT_RESET_ON_PROGRESS=true
      - MCP_REQUEST_MAX_TOTAL_TIMEOUT=60000
      - VIRTUAL_HOST=${DDEV_HOSTNAME}
      - HTTP_EXPOSE=6274:6274,6277:6277
      - HTTPS_EXPOSE=6275:6274,6278:6277
    env_file:
      - .ddev/.env.mcp-inspector
    expose:
      - "6274"
      - "6277"
    volumes:
      - ".:/mnt/ddev_config:ro"
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache git curl &&
        npm install -g @modelcontextprotocol/inspector &&
        echo 'MCP Inspector is starting...' &&
        echo 'Client UI available at: https://${DDEV_HOSTNAME}:6275' &&
        echo 'Proxy Server available at: https://${DDEV_HOSTNAME}:6278' &&
        exec npx @modelcontextprotocol/inspector
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6274/health", "||", "curl", "-f", "http://localhost:6274"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - default
      - ddev_default

networks:
  ddev_default:
    external: true