name: tests
on:
  pull_request:
  push:
    branches: [ main, master, beta, develop ]
    tags: 
      - 'v*.*.*'
      - 'v*.*.*-beta.*'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Validate add-on structure
      run: |
        # Check required files exist
        if [ ! -f "install.yaml" ]; then
          echo "❌ Missing install.yaml"
          exit 1
        fi
        if [ ! -f "docker-compose.mcp-inspector.yaml" ]; then
          echo "❌ Missing docker-compose.mcp-inspector.yaml"
          exit 1
        fi
        if [ ! -f "commands/host/mcp-inspector" ]; then
          echo "❌ Missing commands/host/mcp-inspector"
          exit 1
        fi
        
        # Check that files have required markers
        if ! grep -q "#ddev-generated" install.yaml; then
          echo "❌ install.yaml missing #ddev-generated marker"
          exit 1
        fi
        if ! grep -q "#ddev-generated" docker-compose.mcp-inspector.yaml; then
          echo "❌ docker-compose.mcp-inspector.yaml missing #ddev-generated marker"
          exit 1
        fi
        if ! grep -q "#ddev-generated" commands/host/mcp-inspector; then
          echo "❌ commands/host/mcp-inspector missing #ddev-generated marker"
          exit 1
        fi
        
        echo "✅ Add-on structure validation passed"

  release:
    needs: tests
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') }}
        generate_release_notes: true
        files: |
          README.md
          CHANGELOG.md
          LICENSE